### ISSUE TITLE
probability is non-finite

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/color-vision#106]
https://github.com/phetsims/scenery/issues/529 added a workaround for this, but it should be investigated further. 

See https://github.com/phetsims/scenery/issues/529#issuecomment-193299655 and https://github.com/phetsims/scenery/issues/529#issuecomment-193356849.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/scenery/issues/529#issuecomment-194450950, @ariel-phet said:

> @pixelzoom can you create a sim specific issue to look into this? Mark low priority, feel free to work on if you need something else, but not a major priority at the moment.

**Comment by Luisav1** [comment]
The wavelength was being set to `undefined` for black photons in `SingleBulbPhoton.js` which resulted in a `NaN` value in the probability calculation so now probability is temporarily set to `-1` like so:
```js
if ( photon.wavelength >= 0 ) {
            probability = 1 - Math.abs( filterWavelength - photon.wavelength ) / halfWidth;
          }
          else {
            // negative wavelength thus the photon is black so temporarily set probability to negative value
            probability = -1;
          }
```
Then at the end instead of checking if the value `isFinite` we check if it's negative and set the intensity to 0 if so:
`photon.intensity = ( probability >= 0 ) ? ( ( probability < 0.2 ) ? 0.2 : probability ) : 0;`.

This is fixed now. Closing.
