### ISSUE TITLE
Brightness inconsistency

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/color-vision#163]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1150
This happens in the published version, and may be the intended behavior, but I noticed the inconsistancy.
In most situations, the number of photons reaching the person determines the brightness shown. However, in the case of a filter and the white light the brightness is maximum despite few photons shown reaching the eye. Compare this to the number of photons reaching the eye with the same filter and a matching monocolor light.

**Visuals**
![brightnessame](https://github.com/user-attachments/assets/2d7bf475-8cc8-4af3-b39c-da3574bee9bc)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Color Vision‬
URL: https://phet-dev.colorado.edu/html/color-vision/1.3.0-rc.1/phet/color-vision_all_phet.html
Version: 1.3.0-rc.1 2024-10-02 19:01:19 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Thanks @KatieWoe, I see what you're saying, but I can rationalize the behavior in a slightly different way. The perceived brightness is related to the percentage of relevant photons that pass through the filter, rather than the absolute number.

White light contains photons that are an exact match for the filter, which all make it through. The yellow beam and perceived color are at the max brightness.
![image](https://github.com/user-attachments/assets/5ce912c0-8a6a-4a55-b115-999a16d031c7)

When using a slightly off-color monochromatic light, only a fraction of it can pass through the filter, resulting in reduced brightness.
![image](https://github.com/user-attachments/assets/e97ec788-99e6-47a3-a5b0-5ee24765ac8d)

If we were to scale the brightness based on the raw number of photons, filtered white light would always appear dimmer, because we use the same photon density for the white and monochromatic sources. 

This info from the Teacher Tips may also be helpful: 
>  Each pixel photon represents many photons in the model. At times, color may still be perceived even
when a pixel photon does not precisely hit the eye because the underlying model assumes there is a
beam of photons present.

I don't think we should make any changes here, closing.
