### ISSUE TITLE
invalid aspect ratio for screen icons in navbar

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/color-vision#93]
Screen icons for the navbar must have the same aspect ratio as either Screen.NAVBAR_ICON_SIZE or Screen.HOME_SCREEN_ICON_SIZE. See phetsims/joist#263 (comment). This sim does not, and fails when assertions are enabled.

**Comment by aaronsamuel137** [comment]
Fixed. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
@aaronsamuel137 I'm curious about this required a change to SCALE in FlashlightNode.

**Comment by aaronsamuel137** [comment]
The flashlights in the RGB icons were extending outside of the background rectangle a little bit, so I scaled them a little smaller, otherwise the icon size gained a little height and lost the correct aspect ratio. I could have tried moving the flashlights closer too, but making them a little smaller didn't seem to look bad to me. What do you think?

**Comment by pixelzoom** [comment]
Sounds good, thanks for clarifying. Closing.
